apiVersion: apps/v1
kind: Deployment
metadata:
  name: atlas-portal
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orion-api
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow
spec:
  replicas: 1
