apiVersion: v1
kind: Service
metadata:
  name: apache-web
  labels:
    app.kubernetes.io/name: apache-web
spec:
  selector:
    app.kubernetes.io/name: apache-web
  ports:
    - name: http
      port: 80
      targetPort: 80
