apiVersion: v1
kind: Service
metadata:
  name: atlas-portal
  labels:
    app.kubernetes.io/name: atlas-portal
spec:
  selector:
    app.kubernetes.io/name: atlas-portal
  ports:
    - name: http
      port: 8080
      targetPort: 8080
